openapi: 3.2.0
info:
  title: Kota Embed Sessions API
  version: '1.0'
servers:
- url: https://test.api.kota.io
  description: Test Kota API
  x-fern-server-name: test
- url: https://api.kota.io
  description: Production Kota API
  x-fern-server-name: production
security:
- bearerAuth: []
tags:
- name: Embed Sessions
paths:
  /embed/sessions:
    post:
      tags:
      - Embed Sessions
      summary: Get Embedded SDK token
      description: Retrieve a `token` to authenticate an `employer` or `employee` with the Kota Embedded SDK.
      operationId: CreateEmbedSession
      requestBody:
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/CreateSessionTokenRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateSessionTokenResponse'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
components:
  schemas:
    CreateSessionTokenResponse:
      required:
      - expiry
      - token
      type: object
      properties:
        token:
          type: string
        expiry:
          type: string
          format: date-time
          example: '2024-12-01T00:00:00Z'
      additionalProperties: false
    ProblemDetails:
      type: object
      properties:
        type:
          type:
          - 'null'
          - string
        title:
          type:
          - 'null'
          - string
        status:
          type:
          - 'null'
          - integer
          format: int32
        detail:
          type:
          - 'null'
          - string
        instance:
          type:
          - 'null'
          - string
      additionalProperties: {}
    HttpValidationProblemDetails:
      type: object
      properties:
        type:
          type:
          - 'null'
          - string
        title:
          type:
          - 'null'
          - string
        status:
          type:
          - 'null'
          - integer
          format: int32
        detail:
          type:
          - 'null'
          - string
        instance:
          type:
          - 'null'
          - string
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
      additionalProperties: {}
    CreateSessionTokenRequest:
      required:
      - employer_id
      type: object
      properties:
        employer_id:
          pattern: er_.+
          type: string
          example: er_3b1333d87d9d4fd6ad83ba7f6b0e951a
        employee_id:
          pattern: ee_.+
          type:
          - 'null'
          - string
          example: ee_3b1333d87d9d4fd6ad83ba7f6b0e951a
        external_customer_id:
          type:
          - 'null'
          - string
          description: A unique identifier assigned by the Employer of Record (EoR) platform to the Customer (i.e. the company using the EoR service) for which the employee is employed. This ID groups employees under this Customer, enabling the aggregation of contribution reporting and other values per Customer rather than per legal entity. This parameter is required for Employer Session tokens for EoR platforms.
      additionalProperties: false
  securitySchemes:
    bearerAuth:
      type: http
      description: Authorization header using the Bearer scheme
      scheme: bearer
      x-fern-bearer:
        name: apiKey
        env: KOTA_API_KEY
